schema:
  format:
    openapi: "3.0.0"
  environment_input_type: "S3EnvironmentInput"
  types:
    S3EnvironmentInput:
      type: object
      description: "Input properties for my environment"
      properties:
        name_bucket_1:
          type: String
          description: "Input Name of S3 Environment"
        name_bucket_2:
          type: String
          description: "Input Name of S3 Environment"
          