schema:
  format:
    openapi: "3.0.0"
  environment_input_type: "S3EnvironmentInput"
  types:
    S3EnvironmentInput:
      type: object
      description: "Input properties for my environment"
      properties:
        name_bucket_1:
          type: string
          description: "Name of S3 Bucket"
          default: toanla123-env1
        name_bucket_2:
          type: string
          description: "Name of S3 Bucket"
          default: toanla123-env2